### ISSUE TITLE
Cannot login and blocked

### ISSUE THREAD

**Issue by samuelg78** [mgp25/Chat-API-NET#182] opened 2016-04-16 03:16 UTC
Since 3 hours ago... cannot login and all number are blocked. Anyone same problem?

**Comment by p031985s** [comment] 2016-04-16 03:25
Hi, yes, all my numbers blocked too

**Comment by samuelg78** [comment] 2016-04-16 04:11
@mgp25 @BayrakMustafa .... Please help to check.

**Comment by eaba** [comment] 2016-04-16 04:14
@samuelg78 it is general and I dont think help will come, that soon!

**Comment by samuelg78** [comment] 2016-04-16 04:15
@eaba .... Is the php version affected?

**Comment by eaba** [comment] 2016-04-16 04:17
I guess so.....if you explore, you could fix it!

**Comment by ascrus87** [comment] 2016-04-16 14:07
yes, same here. All my numbers cannot login: not-authorized.

**Comment by BayrakMustafa** [comment] 2016-04-16 14:16
@samuelg78 .... You can try to re-register using API. I got this error a few days ago. I re-register my phone number from API. It worked for me.

**Comment by p031985s** [comment] 2016-04-16 14:20
Are you using PHP or .NET?, i try to re-register and it say Number Blocked, i am using .NET API

**Comment by BayrakMustafa** [comment] 2016-04-16 15:29
I'am using .NET API. When I try to login whatsapp, I got not-authorized error and re-register my number. It is fix my problem. But your problem is different from me. I don't get number blocked error.

**Comment by BayrakMustafa** [comment] 2016-04-16 15:42
@p031985s I try to login now. I got same error not-authorized. I can try to re-register and get number blocked error.

**Comment by eaba** [comment] 2016-04-16 18:10
@BayrakMustafa could this be caused by the whatsapp version?

**Comment by dennisctp** [comment] 2016-04-18 03:06
I tried update with following settings but still getting not-authorized error
WhatsAppVer = "2.12.522";
UserAgent = "WhatsApp/2.12.522 Android/4.3 Device/Xiaomi-HM_1SW";
classesMd5 = "UOlSm7/XlTP/PW0G4wIIdg==";

**Comment by samuelg78** [comment] 2016-04-18 08:10
@dennisctp How did you derive the version, usergent and Md5?

**Comment by dennisctp** [comment] 2016-04-18 08:25
hi, i saw it from another project. but its not working as well.
i'm trying to figure out how to derive the version, useragent and MD5 as well.

i still can't understand the wiki on retrieving token.
you can refer to this :
https://github.com/mgp25/Chat-API/wiki/Token-Generation

please elaborate if u understand any of it

**Comment by oram83** [comment] 2016-04-18 10:03
Same here, I get "unauthorized" and when I try to re-register I get 'blocked number' error.

**Comment by SkySantoro** [comment] 2016-04-18 14:48
I'm blocked and not-authorized usign API....
I tried to get my pass using my device and I got this message :(  ... "Your number 'xxx' is banned from using WhatsApp. Contact support for help." ....

**Comment by samuelg78** [comment] 2016-04-18 17:09
All my previous numbers are been blocked by Whatsapp for using the .net API. I am afraid that we have to use new numbers for testing.

**Comment by dennisctp** [comment] 2016-04-18 17:13
at the moment, do not, i repeat, do not register your number through the api
try register thru the whatsapp app in android n use an extractor to get the password

**Comment by markdates** [comment] 2016-04-18 17:33
If you use the extractor, WP does not block number again using the API?

**Comment by dennisctp** [comment] 2016-04-18 17:37
so far i doesn't get the number blocked message using the API
i never do any registration as other mentioned above.
maybe i'm wrong, but its safer not to register using the API

**Comment by eaba** [comment] 2016-04-18 17:48
how can i use the extractor?

**Comment by dennisctp** [comment] 2016-04-18 17:50
i think a more proper question for getting the password is whether the extractor still works for the latest version. i haven't try that
but for those who are having not-authorized error, please don't re-register using the api at the moment

**Comment by eaba** [comment] 2016-04-18 17:54
Okay thanks

**Comment by dennisctp** [comment] 2016-04-18 17:54
another thing i do is that i make sure all recipient of my messages agreed not to click the report spam.
i made an instruction for them to add my number to their contact so that my number doesn't have a chance to be reported as spam

**Comment by eaba** [comment] 2016-04-18 18:10
My purpose is not to spam, my audience understands this! I only broadcast!
I think my was blocked because my code failed and maintained simultaneous connects with whatsapp, I did fine before that!

Understand how this works, so trust my coding for AI

**Comment by samuelg78** [comment] 2016-04-18 23:50
Where to download the extractor to get the password? Can anyone clarify if the password extractor is working now. 
Is there any android sniffing tools that can sniff whatsapp transaction?

**Comment by markdates** [comment] 2016-04-19 00:40
let's face it, the API is dead. No intention to continue development...

**Comment by markdates** [comment] 2016-04-19 12:54
Delete my comment?!
I said that the API was dead. If not, give signs of life, it's all good. But not eliminate the comments!

**Comment by dennisctp** [comment] 2016-04-19 13:04
@markdates i think you missed the main point here.
we are here to discuss n trying to figure out how to make things work, please keep your give up speech to yourself. we really don't need negativity with no contribution.

btw i tried on android and it seems that the registration method differs now, which is why registering yourself using the API will make your number blocked.
but using the old password won't.

**Comment by markdates** [comment] 2016-04-19 13:09
OK sorry. It was not my intention. It was my frustration.
Then I understand that I can continue to use the latest version of the API without problems, provided you use the correct password? Getting the password with the extractor? or use another method?
Thank you very much and I apologize again.

**Comment by dennisctp** [comment] 2016-04-19 13:12
at this moment, we still need a working version, useragent and token

**Comment by eaba** [comment] 2016-04-19 13:24
Hello @dennisctp  i am currently testing the version and md5 you posted earlier, it is passing at the moment.
I was able to register and login, but I tweaked the registration outside of what the Api provides!

**Comment by eaba** [comment] 2016-04-19 13:28
I am using a different Api than this by @BayrakMustafa

**Comment by eaba** [comment] 2016-04-19 13:46
I will also suggest we give Telegram a lift here: https://github.com/sochix/TLSharp
We can create a big competition that may make WhatsApp more open to developers!

I have my strategies to push my target audience, I mean large audience, to Telegram!
We are begging WhatsApp to long and too much
The ball is in our court, who will play it?

**Comment by Arei15** [comment] 2016-04-19 13:54
@eaba  Different Api?

**Comment by eaba** [comment] 2016-04-19 13:59
Or rather a modified fork of Chat-Api-Net

**Comment by eaba** [comment] 2016-04-19 14:01
I am current still testing, so no hurray yet!

**Comment by samuelg78** [comment] 2016-04-19 16:49
@eaba How did know the way to tweak the registration API? Maybe you can share after you had succeed. There are many people around here which is eager to learn and contribute. Can we install bluestack and learn how whatsapp server really communicate with our phone by sniffing just like fiddler tools?

**Comment by eaba** [comment] 2016-04-19 17:35
First of all, we all need to be on the same page
Change the whatsapp settings to the one posted by @dennisctp 
Request code with a number that has not been registered before
Before registering the code wait more than the time(in seconds) in sms_wait (this is how the official client works).

if you have done this and still get blocked, come back here for the next step!

**Comment by markdates** [comment] 2016-04-20 02:37
Any good news?
Someone knows a tool for Windows or Mac to get the password?

**Comment by eaba** [comment] 2016-04-20 06:31
@markdates no good news if you dont do what i said above!
I have two numbers currently connected, I have disconnected and reconnected several times

**Comment by samuelg78** [comment] 2016-04-20 07:12
I had successfully registered for the moment.... will let it run for 6 hours and post result. Anyone can advise how to derive the classesMd5, WhatsAppVer and UserAgent value? The current playstore version is 2.16 already.... so i am afraid whatsapp may block those runnning old version anytime.

**Comment by eaba** [comment] 2016-04-20 07:21
WhatsAppVer and UserAgent should be easy. 
but for classesMd5, we need tutorial from @mgp25, Though he posted how to in php repo
I could get it to work!

**Comment by dennisctp** [comment] 2016-04-20 12:51
hmm seems like u guys get it thru using the values i posted.
and yet i'm still wondering why i can't connect. lol
glad my post helped u

**Comment by eaba** [comment] 2016-04-20 12:54
Are u still having issues at your end?

**Comment by eaba** [comment] 2016-04-20 13:01
Hello @mgp25 what does `file.apk` stand for in `classes.exe file.apk`
Is it the WhatsApp.apk?

**Comment by mgp25** [comment] 2016-04-20 13:02
@eaba yes

**Comment by eaba** [comment] 2016-04-20 13:04
Okay, so that is the magic!!!!!
Thanks alot

**Comment by dennisctp** [comment] 2016-04-20 13:14
@eaba  ya, i'm still getting not-authorized error

**Comment by eaba** [comment] 2016-04-20 13:26
@dennisctp do you know what mcc, mnc, cc, lg, lc standard for?
You need to edit that in the registration function for your sim provider and country!

**Comment by eaba** [comment] 2016-04-20 13:29
For WhatsAppVer = "2.16.35"
classesMd5 = "leYKMPReumjrfQVVBrJcag=="

I have not tested this and do not know if this api will work for it

**Comment by dennisctp** [comment] 2016-04-20 14:07
@eaba thanks for the tips,
i tweaked the registration for my country and successfully re-registered and login.

**Comment by eaba** [comment] 2016-04-20 14:15
So, maybe WhatsApp now validate each number at their server-side!
This is what I actually do in my SMS application
I can upload a file containing all the networks in the world if i am permitted by @mgp25

**Comment by samuelg78** [comment] 2016-04-20 14:44
Good news.... its still running without errors.

**Comment by samuelg78** [comment] 2016-04-20 14:45
@eaba .... i got the classesMd5 value using mgp25 classes.exe

**Comment by Arei15** [comment] 2016-04-20 14:46
@samuelg78  i don't belive, what you using?

**Comment by samuelg78** [comment] 2016-04-20 14:48
Request code with a number that has not been registered before
Before registering the code wait more than the time(in seconds) in sms_wait (this is how the official client works)
Use the following:
WhatsAppVer = "2.12.522";
UserAgent = "WhatsApp/2.12.522 Android/4.3 Device/Xiaomi-HM_1SW";
classesMd5 = "UOlSm7/XlTP/PW0G4wIIdg==";

**Comment by eaba** [comment] 2016-04-20 14:48
@Arei15 you dont believe what?

**Comment by samuelg78** [comment] 2016-04-20 14:50
@eaba How can we really prevent the numbers getting blocked? Maybe a warning or notification before the numbers get blocked

**Comment by eaba** [comment] 2016-04-20 14:56
I believe your purpose for using the API is the key issue and you also need to read the php repo wiki and closed issues to understand how!
Since you know how to generate ClassesMd5, you should not ever have issues!
Also submitting the mcc, mnc etc of your sim provider is also key.

BE UNHUMAN

**Comment by dennisctp** [comment] 2016-04-20 15:19
@samuelg78 maybe u can try to re-register the blocked number from a phone using the official apps? 

actually i didn't use a fresh number. 
i'm using my existing number that had been registered, but its not blocked.
after i re-register with the api with a little tweak mentioned earlier, i'm able to get the password and login.

@eaba where can i get the classes.exe ?

**Comment by dennisctp** [comment] 2016-04-20 15:25
@eaba regarding "I can upload a file containing all the networks in the world"
actually there's a file in WhatsAppApi/Parser folder, named countries.csv
the file already contained all the MNC, MCC, CC, ISO3166, ISO639 needed.

its just that the PhoneNumber new method does not have a complete select statement to auto set these values

**Comment by eaba** [comment] 2016-04-20 15:37
With the way the PhoneNumber works, it is limited to one network provider per country (i could be wrong). So if my provider is AComs and the APi contains BComs for my country, the BComs is what is used. Trust me, if i were WhatsApp i will detect this!

**Comment by eaba** [comment] 2016-04-20 15:38
@dennisctp here https://github.com/mgp25/classesMD5-64

**Comment by samuelg78** [comment] 2016-04-20 16:30
@dennisctp i had tried to re-register the old number but it had been blocked. Anyway my new number got blocked too after running for 8hours ... So it is still not working...

**Comment by eaba** [comment] 2016-04-20 16:41
@samuelg78 now  try registering another number by tweaking the registration function like @dennisctp did for your sim provider and country!

Also what did you do, that you got blocked?

**Comment by eaba** [comment] 2016-04-20 16:41
I have been running my for two days now!

**Comment by dennisctp** [comment] 2016-04-20 16:46
@samuelg78  are u doing something inhuman like sending message every second etc ?
i tried to login with my fix, and now it seems that i'm getting not-authorized error all over again

**Comment by dennisctp** [comment] 2016-04-20 16:47
@eaba  are u using the version that i provide or using the one u generated using the classes.exe method ?

**Comment by samuelg78** [comment] 2016-04-20 16:48
I let it run for 8 hours....my project poll for new message every seconds and reply to sender when received new messages..... i using the 2.12.522 version

**Comment by eaba** [comment] 2016-04-20 16:48
I am using the one you provided! You guys could be doing something wrong! Could you paste your code here?

**Comment by dennisctp** [comment] 2016-04-20 16:49
@eaba i think once u logout, you will be unable to login again and you will get the not-authorized error all over again

**Comment by eaba** [comment] 2016-04-20 16:49
A real human wont read messages almost instantly, though I tweaked SendMessageRecieved function

**Comment by eaba** [comment] 2016-04-20 16:50
I do logout at interval but not at a fixed interval

**Comment by dennisctp** [comment] 2016-04-20 16:51
maybe whatsapp is watching this thread.
whatever setting we post, they will block it =.='''

**Comment by eaba** [comment] 2016-04-20 16:52
Post your code

**Comment by eaba** [comment] 2016-04-20 16:53
I disconnect then wait upto an hour before reconnecting

**Comment by samuelg78** [comment] 2016-04-20 16:54
@dennisctp ....Yours got blocked too?

**Comment by p031985s** [comment] 2016-04-20 16:54
I am using 2.12.522 and it is working... When i try to register more than 2 numbers from 1 IP, new numbers get blocked, when i try to register from 1 IP from other country, the number get block even if you have registered before and only you are going to use it... Meaning, you cannot use an international IP... i hope it helps.

**Comment by eaba** [comment] 2016-04-20 16:56
@p031985s you are wrong!

**Comment by dennisctp** [comment] 2016-04-20 16:56
@samuelg78 
i don't get block, but i'm getting not-authorized error

@p031985s 
in your case, i suspect they are trying to match and verify the IP with the phone number provided.
but i registered 2 numbers with same IP and i'm alright

**Comment by samuelg78** [comment] 2016-04-20 16:58
maybe we can communicate elsewhere ....

@dennisctp "Log In Failed: not-authorized "?

**Comment by p031985s** [comment] 2016-04-20 16:58
@eaba ok, @dennisctp i registered 2 numbers and they are working but i cannot register more, all i try to register get blocked.

**Comment by dennisctp** [comment] 2016-04-20 16:59
the settings i post no longer work.
you guys need to figure out a way to find your own settings.
i suspect every setting that we post will be block.

**Comment by samuelg78** [comment] 2016-04-20 16:59
For me.... is that new numbers will run fine for about 8 hours..... then got blocked

**Comment by eaba** [comment] 2016-04-20 17:00
@mgp25 you need to say something and i know you are there

**Comment by dennisctp** [comment] 2016-04-20 17:01
@eaba i think its whatsapp messing with us.
we are better off keeping the settings off this page (or any public page)

**Comment by eaba** [comment] 2016-04-20 17:02
@samuelg78 dont stay online for very long, for how long did you stay online?

**Comment by samuelg78** [comment] 2016-04-20 17:03
24 hours

**Comment by eaba** [comment] 2016-04-20 17:04
@dennisctp let see you log and a sample of your code

**Comment by samuelg78** [comment] 2016-04-20 17:05
I can confirm new numbers will run fine...... but you stay online like 8 hours..... u will get blocked.

**Comment by samuelg78** [comment] 2016-04-20 17:05
And u can never get unblocked

**Comment by eaba** [comment] 2016-04-20 17:06
@samuelg78 as you stayed online for 24hrs without disconnecting?
If so, official client cant do that or real human

**Comment by dennisctp** [comment] 2016-04-20 17:06
i don't stay online that long, and i'm still getting not-authorized error

**Comment by eaba** [comment] 2016-04-20 17:07
You will get unblocked in about two months

**Comment by dennisctp** [comment] 2016-04-20 17:07
@eaba i don't have much log, 
my programs just send me this line in email 
whatsapp login failed  data :not-authorized<BR>whatsapp version:2.12.522

**Comment by samuelg78** [comment] 2016-04-20 17:08
The 2.12.522 version is working..... but like i said...... if online too long will get blocked

**Comment by eaba** [comment] 2016-04-20 17:11
I dont know what else to say @mgp25, the php repo wiki and close issues are there,
if encounter the same issue i will let you all know

**Comment by samuelg78** [comment] 2016-04-20 17:14
My flow of program is that: Every sec it will check new message and login status, if login status is offline will reconnect. If new message received will post to my api and reply the sender

**Comment by eaba** [comment] 2016-04-20 17:18
Your use case is different from mine, my use case is to receive message only and send only broadcast message

**Comment by samuelg78** [comment] 2016-04-20 17:20
@eaba Have you tried to be online for 8hours continuously?

**Comment by eaba** [comment] 2016-04-20 17:21
There is no grantee that i wont be blocked, but for now i live to fight another day!
Also when something is bound to fail, you seek an alternative and  hope you all find an alternative as @mgp25  wont permit me to mention here

**Comment by eaba** [comment] 2016-04-20 17:22
I only reconnect any time between 25mins to 60mins and disconnect any time between 30min to 60mins

**Comment by eaba** [comment] 2016-04-20 17:23
And i just reconnected not very quite long

**Comment by samuelg78** [comment] 2016-04-20 17:24
@eaba so the php does not have this issue?

**Comment by dennisctp** [comment] 2016-04-20 17:24
i just run like 3 times for testing, and i get blocked now
and my program runs within 5 minutes just once per day ...

**Comment by samuelg78** [comment] 2016-04-20 17:24
@dennisctp what is the flow of use?

**Comment by eaba** [comment] 2016-04-20 17:25
@dennisctp are you really using the mnc for your mobile carrier?

**Comment by eaba** [comment] 2016-04-20 17:26
Every mobile carrier in the world have unique mcc and mnc combined

**Comment by dennisctp** [comment] 2016-04-20 17:26
@eaba i do, it did works after you told me about tweaking the mnc and such.

its after samuelg78 reported that it stopped working, so i tried to run mine, and bam, mine doesn't work as well

PS - i didn't run the program after the success trial, and before samuelg78 report that its not working anymore

**Comment by eaba** [comment] 2016-04-20 17:27
@samuelg78 @mgp25 is experiencing complaint at the php repo

**Comment by eaba** [comment] 2016-04-20 17:29
Am smiling and feeling @mgp25  knows what is going on

**Comment by samuelg78** [comment] 2016-04-20 17:30
Smiling.....really?

**Comment by dennisctp** [comment] 2016-04-20 17:30
@eaba  can we talk in email ? my user name @ yahoo

**Comment by samuelg78** [comment] 2016-04-20 17:33
@dennisctp recv?

**Comment by eaba** [comment] 2016-04-20 17:33
Let me open a fake email address for that

**Comment by samuelg78** [comment] 2016-04-20 17:36
@eaba whats the email?

**Comment by eaba** [comment] 2016-04-20 17:36
Also i am using the version provided by @BayrakMustafa

**Comment by samuelg78** [comment] 2016-04-20 17:37
Me too

**Comment by eaba** [comment] 2016-04-20 17:37
wessimiduke@gmail.com

**Comment by dennisctp** [comment] 2016-04-20 17:38
i got it u can delete the email

**Comment by samuelg78** [comment] 2016-04-20 17:39
@dennisctp ..... u received my email?

**Comment by eaba** [comment] 2016-04-20 17:41
I will check that now, please be patient

**Comment by samuelg78** [comment] 2016-04-20 17:43
@eaba .... ur email is undeliverable

**Comment by eaba** [comment] 2016-04-20 17:47
google says it does not exist

**Comment by eaba** [comment] 2016-04-20 17:47
strange

**Comment by eaba** [comment] 2016-04-20 17:51
questswa at gmail

**Comment by mgp25** [comment] 2016-04-20 18:42
.NET API is way to outdated, although it will work for sometime, it will stop eventually.

**Closed by mgp25** 2016-04-20 18:42 UTC

**Comment by psanket007** [comment] 2016-04-22 05:46
We have use .Net API Whatsapp version (WhatsAppVer = "2.16.13") 
but still  getting ERROR :  "{"status":"fail","reason":"bad_token"}"

**Comment by eaba** [comment] 2016-04-22 09:33
2.12.556
WhatsApp/2.12.556 Android/4.3 Device/Xiaomi-HM_1SW
ry9Xz6kVioQctwA3G9z62Q==

Chat-Api-Net is greatly outdated!

**Comment by Arei15** [comment] 2016-04-22 11:01
@eaba But how to use?

**Comment by eaba** [comment] 2016-04-22 11:15
Are you new to this API?
Update the WhatsAppConstants.cs
`public const string WhatsAppVer = "2.12.556";`
`public const string UserAgent = "WhatsApp/2.12.556 Android/4.3 Device/Xiaomi-HM_1SW";`

AND WaToken.GenerateTokenAndroid
`var classesMd5 = "ry9Xz6kVioQctwA3G9z62Q==";`

**Comment by Arei15** [comment] 2016-04-22 11:20
@eaba if Chat-Api-Net is greatly outdated!, but  how to use? We don't have analogs.

**Comment by eaba** [comment] 2016-04-22 11:31
Use this https://github.com/BayrakMustafa/WhatsApp-API-NET

**Comment by Arei15** [comment] 2016-04-22 12:30
This  https://github.com/BayrakMustafa/WhatsApp-API-NET don't works. WhatsApp-API-NET blocked my number. @eaba  @BayrakMustafa

**Comment by eaba** [comment] 2016-04-22 12:55
You did something not human, try a new number

**Comment by samuelg78** [comment] 2016-04-22 15:19
@eaba .... Anything not human about my code?

**Comment by eaba** [comment] 2016-04-22 16:22
Hi @samuelg78 i have actually not had time to go through your code!
But the thing is, I also got one of my number blocked earlier today!
I asked myself why and what i did that got it blocked!
First when the update to PHP version was made by @oxtrycatch, i immediately deleted my old password and attempted requesting a new one (i think i was still connected while I requested a new code), I got the code but when I tried registering it i got try_after:3600 (1 hour) and I did but then my number got blocked!

I am saying this to encourage you to take responsibility for your code and issues! It is actually very tough helping remotely and without much information @mgp25

**Comment by dennisctp** [comment] 2016-04-22 16:56
i also got my number blocked by running only once, and sending only 4 messages to my self,
the message being
debug start
message sent : 0
email sent : 0
debug end

thats all and it logged out
in between the messages its a few seconds for my code to go through some remote db operation.

after successfully running for only ONCE
i got blocked before i can do it the second time.

**Comment by eaba** [comment] 2016-04-22 17:22
I think a time out with the PHP version will save a lot of issues here!
There are a lot of stuffs buried over there, do the digging! @mgp25

**Comment by eaba** [comment] 2016-04-22 17:24
And i am very certain @mgp25 wont help with a full log submitted!
Lets try paste our logs here, logging can be enable at the WhatsAppApi contructor

**Comment by eaba** [comment] 2016-04-22 17:44
@samuelg78 take a look at this issue opened by me #178

**Comment by softcode2** [comment] 2016-04-24 13:34
@eaba any news ?

**Comment by samuelg78** [comment] 2016-05-03 17:20
@eaba Pls let me know the ping intervals and re-connect? Thks

**Comment by eaba** [comment] 2016-05-03 17:29
@samuelg78  at the moment i am re-writing my code and based on my study of the api and studying how the current WhatsApp official client work, i want to believe it should be:
```
var diff = (DateTime.Now.Substract(lastTreeRead).TotalSeconds;
if(diff >= variable)
{
ping;
counter++;
}
```
I have not tested this yet!

**Comment by deniwidiatmoko** [comment] 2016-10-28 03:22
hy guys,

i have issue status 'fail reason old_version' ,
version whatsapp 2.16.310. 
 anyone can help me ?
